name: "bump versions"

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Checkout v4"
        uses: actions/checkout@v4
      -
        name: "Update versions.json"
        run: |
          wordpress_version=`curl "https://api.github.com/repos/WordPress/WordPress/tags?per_page=1" | jq .[0].name`
          sqlite_database_integration_version=`curl "https://api.github.com/repos/WordPress/sqlite-database-integration/tags?per_page=1" | jq .[0].name`
          echo "{\"wordpress_version\":${wordpress_version},\"sqlite_database_integration_version\":\"${sqlite_database_integration_version:2}}" > versions.json
          git diff
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add versions.json
            git commit -m "Auto versions bump"
            git push
          else
            echo "No changes. No push"
          fi
