name: "bump versions"

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        name: "Checkout v4"
        uses: actions/checkout@v4
      -
        name: "Update versions.json"
        run: |
          wordpress_version=`curl "https://api.github.com/repos/WordPress/WordPress/tags?per_page=1" | jq .[0].name`
          sqlite_database_integration_version=`curl "https://api.github.com/repos/WordPress/sqlite-database-integration/tags?per_page=1" | jq .[0].name`
          echo "{\"wordpress_version\":${wordpress_version},\"sqlite_database_integration_version\":\"${sqlite_database_integration_version:2}}" > versions.json
          git diff
          if [[ ! `git status --porcelain` ]]; then
            echo "No changes. No push"
            exit 1
          fi
      -
        name: "Push changes to branch main"
        uses: stefanzweifel/git-auto-commit-action@v5
