name: "bump versions"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        name: "Checkout v4"
        uses: actions/checkout@v4
      -
        name: "Update versions.json"
        id: update_versions_file
        run: |
          wordpress_version=`curl "https://api.github.com/repos/WordPress/WordPress/tags?per_page=1" | jq .[0].name`
          sqlite_database_integration_version=`curl "https://api.github.com/repos/WordPress/sqlite-database-integration/tags?per_page=1" | jq .[0].name`
          sqlite_database_integration_version="\"${sqlite_database_integration_version:2}"
          echo "{\"wordpress_version\":${wordpress_version},\"sqlite_database_integration_version\":${sqlite_database_integration_version}}" > versions.json
          git diff
          echo "has_update=`git status --porcelain`" >> "$GITHUB_OUTPUT"
      -
        name: "Push changes to branch main"
        uses: stefanzweifel/git-auto-commit-action@v5
        if:  ${{ steps.update_versions_file.outputs.has_update != '' }}
        with:
          commit_message: "Auto bump versions"
          file_pattern: 'versions.json'
